### ISSUE TITLE
获取分类列表过期导致无法获取句子

### ISSUE THREAD

**Issue by greenhat616** [hitokoto-osc/hitokoto-api#237]
```
2020-11-26T10:40:37.938Z [23428] - error: [hitokoto.updateCategories] occur error while updating, error details:
2020-11-26T10:40:37.938Z [23428] - error:  message=tmp is not iterable, stack=TypeError: tmp is not iterable
    at updateCategories (/root/Programs/hitokoto-osc/hitokoto-api/src/controllers/hitokoto/_utils.js:83:28)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async exports.tickUpdateCategories (/root/Programs/hitokoto-osc/hitokoto-api/src/controllers/hitokoto/_utils.js:111:12)
    at async module.exports (/root/Programs/hitokoto-osc/hitokoto-api/src/controllers/hitokoto/entry.js:14:3)
    at async logger (/root/Programs/hitokoto-osc/hitokoto-api/src/logger.js:55:7)
    at async /root/Programs/hitokoto-osc/hitokoto-api/.yarn/cache/koa-compress-npm-5.0.1-8453c7382d-57844bfaa1.zip/node_modules/koa-compress/lib/index.js:38:5
    at async bodyParser (/root/Programs/hitokoto-osc/hitokoto-api/.yarn/cache/koa-bodyparser-npm-4.3.0-73f6acb252-8261981504.zip/node_modules/koa-bodyparser/index.js:95:5)
    at async _jsonp (/root/Programs/hitokoto-osc/hitokoto-api/.yarn/cache/@hitokoto-koa-jsonp-npm-3.0.7-3bfe627df6-82da1bfc02.zip/node_modules/@hitokoto/koa-jsonp/lib/jsonp.js:17:5)
    at async /root/Programs/hitokoto-osc/hitokoto-api/.yarn/cache/koa-query-pretty-npm-0.3.0-16a3c4d62e-2b6d7f7904.zip/node_modules/koa-query-pretty/lib/index.js:49:3
    at async sendMail (/root/Programs/hitokoto-osc/hitokoto-api/src/middlewares/MailError.js:16:5)
```

**Comment by greenhat616** [comment]
当句子指定一个一些分类不存在长度区间的句子，会间断性的返回400

**Comment by greenhat616** [comment]
初步推断是 Redis 连接时的问题，需要具体确认细节。

**Comment by greenhat616** [comment]
问题更新。
初步推断是更新器的问题.
![image](https://user-images.githubusercontent.com/41122242/106702088-bf56f380-6622-11eb-8610-47e6d132b820.png)
![image](https://user-images.githubusercontent.com/41122242/106702156-d7c70e00-6622-11eb-89b2-07b6c8f88076.png)
