### ISSUE TITLE
针对docker-compose运行过程中发现超时的问题

### ISSUE THREAD

**Issue by wuchenchina** [hitokoto-osc/hitokoto-api#628]
执行`docker compose logs -f`后截取到的日志如下
```
hitokoto_api  |  hitokoto v1.7.1 © 2024 All Rights Reserved.     Powered by teng-koa 
hitokoto_api  | 
hitokoto_api  |  我们一路奋战，不是为了改变世界，而是为了不让世界改变我们。 
hitokoto_api  | 2024-08-14T07:20:35.153Z [35] - error: RequestError: read ECONNRESET
hitokoto_api  |     at ClientRequest.<anonymous> (/usr/src/app/node_modules/.store/got-npm-11.8.6-89e7cd5d67/package/dist/source/core/index.js:970:111)
hitokoto_api  |     at Object.onceWrapper (node:events:629:26)
hitokoto_api  |     at ClientRequest.emit (node:events:526:35)
hitokoto_api  |     at origin.emit (/usr/src/app/node_modules/.store/@szmarczak-http-timer-npm-4.0.6-6ace00d82d/package/dist/source/index.js:43:20)
hitokoto_api  |     at TLSSocket.socketErrorListener (node:_http_client:495:9)
hitokoto_api  |     at TLSSocket.emit (node:events:514:28)
hitokoto_api  |     at emitErrorNT (node:internal/streams/destroy:151:8)
hitokoto_api  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
hitokoto_api  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
hitokoto_api  |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
hitokoto_api  | 2024-08-14T07:20:35.159Z [35] - error: [init] error was thrown while initializing, processes exiting.
hitokoto_api  | 2024-08-14T07:20:35.162Z [35] - error: [core] received exit code: 1, process will be destroyed.
hitokoto_api  | 2024-08-14T07:20:35.163Z [35] - info: [core] Web server is shut down, Bye!
hitokoto_api exited with code 0
```
不清楚可不可以在`docker-compose.yaml`中增加`proxy`段？（个人拙见）或许使用代理就行了？

**Comment by LoCCai** [comment]
请问这个问题你现在解决了吗
